# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

site_name: 'Exploring Pravega'
site_url: 'https://pravega.io/'
site_description: 'Documentation to help you get familiar with Pravega'

repo_url: 'https://github.com/pravega/pravega'
edit_uri: 'tree/master/documentation/src/docs'

# theme: 'readthedocs'
theme:
  name: material
  custom_dir: custom_theme

  # 404 page
  #static_templates:
  #  - 404.html

  # Necessary for search to work properly
  #include_search_page: false
  #search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  #language: en
  #font:
  #  text: Roboto
  #  code: Roboto Mono
  favicon: assets/favicon.ico
  #icon:
  #  logo: logo


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Overview: 'index.md'
  - Quick Start: 'getting-started/quick-start.md'
  - Getting Started:
    - 'Running a Sample Application': 'getting-started/getting-started.md'
    - 'Deploying Pravega on Kubernetes': 'getting-started/pravega-on-kubernetes-101.md'
    - 'Using Flink': 'flink-connectors/documentation/src/docs/dev-guide.md'
    - 'Using Spark': 'spark-connectors/documentation/src/docs/getting-started.md'
    - 'Using Schema Registry': 'schema-registry/documentation/src/docs/getting-started.md'
  - Understanding Pravega:
    - 'Concepts': 'pravega-concepts.md'
    - 'Terminology': 'terminology.md'
    - 'Key Features': 'key-features.md'
    - 'FAQ': 'faq.md'
    - 'Segment Store Service': 'segment-store-service.md'
    - 'Segment Containers': 'segment-containers.md'
    - 'Controller Service': 'controller-service.md'
    - 'Wire Protocol': 'wire-protocol.md'
    - 'StateSynchronizer': 'state-synchronizer-design.md'
    - 'Reader Groups': 'reader-group-design.md'
    - 'Watermarking': 'watermarking.md'
  - Developing Applications:
    - '1st Code Walkthrough': 'beginner_dev_guide.md'
    - 'Client & Stream Semantics': 'dev-guide/clients-and-streams.md'
    - 'Event Reader and Writer': 'basic-reader-and-writer.md'
    - 'Reader Group notifications': 'reader-group-notifications.md'
    - 'State Synchronizer': 'state-synchronizer.md'
    - 'Transactions': 'transactions.md'
    - 'StreamCuts': 'streamcuts.md'
    - 'Client APIs': 'javadoc.md'
    - 'Controller REST API': 'rest/restapis.md'
    - 'Working with Metrics': 'metrics.md'
    - 'Working with Schema Registry': 'schema-registry/documentation/src/docs/pravega-applications.md'
  - Ecosystem:
    - 'Connectors':
      - 'Overview': 'connectors.md'
      - 'Flink Connector':
        - Overview: 'flink-connectors/documentation/src/docs/index.md'
        - Quick Start: 'flink-connectors/documentation/src/docs/quickstart.md'
        - Features:
          - 'Streaming': 'flink-connectors/documentation/src/docs/streaming.md'
          - 'Batch': 'flink-connectors/documentation/src/docs/batch.md'
          - 'Table API': 'flink-connectors/documentation/src/docs/table-api.md'
        - Metrics: 'flink-connectors/documentation/src/docs/metrics.md'
        - Configurations: 'flink-connectors/documentation/src/docs/configurations.md'
        - Serialization: 'flink-connectors/documentation/src/docs/serialization.md'
      - 'Spark Connector':
        - Overview: 'spark-connectors/documentation/src/docs/overview.md'
        - Samples: 'spark-connectors/documentation/src/docs/samples.md'
        - Configuration: 'spark-connectors/documentation/src/docs/configuration.md'
        - Building the Connector: 'spark-connectors/documentation/src/docs/build-connector.md'
        - Limitations: 'spark-connectors/documentation/src/docs/limitations.md'
        - Source Code: 'https://github.com/pravega/spark-connectors/blob/master/README.md'
      - 'Hadoop Connector': 'https://github.com/pravega/hadoop-connectors/blob/master/README.md'
      - 'Presto Connector': 'https://github.com/pravega/presto-connector/blob/main/README.md'
      - 'Boomi Connector': 'https://github.com/pravega/boomi-connector/blob/master/README.md'
      - 'NiFi Connector': 'https://github.com/pravega/nifi-pravega/blob/master/README.md'
    - Client Bingings: 'bindings.md'
    - Tools:
      - 'User CLI': 'https://github.com/pravega/pravega/blob/master/cli/user/README.md'
      - 'Gateways': 'gateways.md'
      - 'Kafka Adapter': 'https://github.com/pravega/kafka-adapter/blob/master/README.md'
      - 'Keycloak Security Plugin': 'https://github.com/pravega/pravega-keycloak/blob/master/README.md'
  - 'Managing Schemas':
    - 'Overview': 'schema-registry/documentation/src/docs/overview.md'
    - 'Schema Registry Concepts': 'schema-registry/documentation/src/docs/schema-registry-concepts.md'
    - 'Using Schema Registry SDK':
      - 'Java API Reference': 'schema-registry/documentation/src/docs/javadoc.md'
      - 'REST API': 'schema-registry/documentation/src/docs/rest-documentation.md'
    - 'Security': 'schema-registry/documentation/src/docs/security.md'
    - 'Deployment': 'schema-registry/documentation/src/docs/installation-guide.md'
  - 'Deployment':
    - 'Overview': 'deployment/deployment.md'
    - 'Running Locally': 'deployment/run-local.md'
    - 'Manual Install': 'deployment/manual-install.md'
    - 'Kubernetes (Helm)': 'pravega-operator/charts/pravega/README.md'
    - 'Kubernetes (custom)': 'pravega-operator/doc/manual-installation.md'
    - 'Docker Swarm': 'deployment/docker-swarm.md'
    - 'DC/OS': 'deployment/dcos-install.md'
    - 'AWS': 'deployment/aws-install.md'
  - Admin Guide:
    - 'Cluster Dependencies': 'admin-guide/cluster-dependencies.md'
    - 'Number of Segment Containers': 'admin-guide/num-containers.md'
    - 'Segment Store Cache and Memory': 'admin-guide/segmentstore-memory.md'
    - 'Durable Log Configuration': 'admin-guide/durable-log-config.md'
    - 'Right-Sizing Long-Term Storage': 'admin-guide/lts-right-sizing.md'
    - 'Admin CLI': 'https://github.com/pravega/pravega/blob/master/cli/admin/README.md'
    - 'Security':
      - 'Overview': 'security/pravega-security-authorization-authentication.md'
      - 'Authentication/Authorization Plugin': 'auth/auth-plugin.md'
      - 'Client Auth Interface': 'auth/client-auth.md'
      - 'Configurations': 'security/pravega-security-configurations.md'
      - 'Encryption': 'security/pravega-security-encryption.md'
      - 'Standalone Mode': 'security/securing-standalone-mode-cluster.md'
      - 'Distributed Mode': 'security/securing-distributed-mode-cluster.md'
    - 'Kubernetes Operations':
      - 'Operators': 'admin-guide/operators.md'
      - 'Pravega Configuration': 'pravega-operator/doc/configuration.md'
      - 'Upgrade Pravega': 'pravega-operator/doc/upgrade-cluster.md'
  - Contributing:
    - 'Coding guildelines': 'contributing.md'
    - 'Pravega Roadmap': 'roadmap.md'
    - 'Join the Community': 'join-community.md'
extra:
    version: 0.1

google_analytics: ['UA-1508605-1', 'pravega.io']
