# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

site_name: 'Exploring Pravega'
site_url: 'https://pravega.io/'
site_description: 'Documentation to help you get familiar with Pravega'

repo_url: 'https://github.com/pravega/pravega'
edit_uri: 'tree/master/documentation/src/docs'

# theme: 'readthedocs'
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Overview: 'index.md'
  - Guides:
      - Quick Start: 'getting-started/quick-start.md'
      - Getting Started: 'getting-started.md'
      - Admin Guide:
        - 'Cluster Overview': 'getting-started/admin-guide.md'
        - 'Install the Operator': 'pravega-operator/charts/pravega-operator/README.md'
        - 'Install a Cluster': 'pravega-operator/charts/pravega/README.md'
        - 'Upgrade Pravega': 'pravega-operator/doc/operator-upgrade.md'
      - Dev Guide:
        - '1st Code Walk through': 'beginner_dev_guide.md'
  - Understanding Pravega:
      - 'Pravega Concepts': 'pravega-concepts.md'
      - 'Terminology': 'terminology.md'
      - 'Key Features': 'key-features.md'
      - 'Pravega FAQ': 'faq.md'
      - 'Segment Store Service': 'segment-store-service.md'
      - 'Segment Containers': 'segment-containers.md'
      - 'Controller Service': 'controller-service.md'
      - 'Wire Protocol': 'wire-protocol.md'
      - 'StateSynchronizer': 'state-synchronizer-design.md'
      - 'Reader Groups': 'reader-group-design.md'
      - 'Watermarking': 'watermarking.md'

  - Developing Pravega Applications:
      - 'Java API Reference': 'javadoc.md'
      - 'REST API - Controller': 'rest/restapis.md'
      - 'Pravega Connectors': 'connectors.md'
      - 'Flink Connectors':
        - Overview: 'flink-connectors/documentation/src/docs/index.md'
        - Getting Started: 'flink-connectors/documentation/src/docs/getting-started.md'
        - Quick Start: 'flink-connectors/documentation/src/docs/quickstart.md'
        - Features:
            - 'Streaming': 'flink-connectors/documentation/src/docs/streaming.md'
            - 'Batch': 'flink-connectors/documentation/src/docs/batch.md'
            - 'Table API': 'flink-connectors/documentation/src/docs/table-api.md'
        - Metrics: 'flink-connectors/documentation/src/docs/metrics.md'
        - Configurations: 'flink-connectors/documentation/src/docs/configurations.md'
        - Serialization: 'flink-connectors/documentation/src/docs/serialization.md'
      - 'Working with Reader and Writer': 'basic-reader-and-writer.md'
      - 'Working with Reader Group notifications': 'reader-group-notifications.md'
      - 'Working with State Synchronizer': 'state-synchronizer.md'
      - 'Working with Transactions': 'transactions.md'
      - 'Working with StreamCuts': 'streamcuts.md'
  - Running Pravega:
      - 'Deployment Overview': 'deployment/deployment.md'
      - 'Running Locally': 'deployment/run-local.md'
      - 'Manual Install': 'deployment/manual-install.md'
      - 'Deployment on Kubernetes': 'deployment/kubernetes-install.md'
      - 'Deployment on Docker Swarm': 'deployment/docker-swarm.md'
      - 'Deployment on DC/OS': 'deployment/dcos-install.md'
      - 'Running in the Cloud (AWS)': 'deployment/aws-install.md'
      - 'Pravega Metrics': 'metrics.md'
  - Pravega Security:
      - 'Pravega Authentication/Authorization Plugin': 'auth/auth-plugin.md'
      - 'Client Auth Interface': 'auth/client-auth.md'
      - 'Pravega Security Authorization/Authentication': 'security/pravega-security-authorization-authentication.md'
      - 'Pravega Security Configurations': 'security/pravega-security-configurations.md'
      - 'Pravega Security Encryption': 'security/pravega-security-encryption.md'
      - 'Securing Pravega in Standalone Mode': 'security/securing-standalone-mode-cluster.md'
      - 'Securing Pravega in Distributed Mode': 'security/securing-distributed-mode-cluster.md'
  - Contributing to Pravega:
      - 'Coding guildelines': 'contributing.md'
      - 'Pravega Roadmap': 'roadmap.md'
      - 'Join the Community': 'join-community.md'
extra:
    version: 0.1

google_analytics: ['UA-1508605-1', 'pravega.io']
