# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]

    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - name: Restore local Gradle & Maven cache
      uses: actions/cache@v2.1.0
      with:
        path: |
          .gradle
          ~/.gradle
          ~/.m2
        key: gradle-m2-java-${{ matrix.java }}
        restore-keys: |
          gradle-m2-java-
          gradle-m2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - name: Javadoc with Gradle
      run: ./gradlew javadocs
    - name: Rat, Checkstyle & Spotbugs with Gradle
      run: ./gradlew rat checkstyleMain checkstyleTest spotbugsMain spotbugsTest

  unit:

    needs: build
    runs-on: ubuntu-latest

    name: Unit Tests on Java 11
    steps:
    - uses: actions/checkout@v1
    - name: Restore local Gradle & Maven cache
      uses: actions/cache@v2.1.0
      with:
        path: |
          .gradle
          ~/.gradle
          ~/.m2
        key: gradle-m2-java-11
        restore-keys: |
          gradle-m2-java-
          gradle-m2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Unit tests with Gradle
      run: ./gradlew test --exclude-task test:integration:test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15

  integration:

    needs: build
    runs-on: ubuntu-latest

    name: Integration Tests on Java 11
    steps:
    - uses: actions/checkout@v1
    - name: Restore local Gradle & Maven cache
      uses: actions/cache@v2.1.0
      with:
        path: |
          .gradle
          ~/.gradle
          ~/.m2
        key: gradle-m2-java-11
        restore-keys: |
          gradle-m2-java-
          gradle-m2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Integration tests with Gradle
      run: ./gradlew test:integration:test
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
